apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-g2-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-g2-1
  template:
    metadata:
      labels:
        app: consumer-g2-1
    spec:
      containers:
      - name: consumer-g2-1
        image: github.com/weak-head/go-kafka-test/consumer:0.0.1
        env:
        - name: kafkaURL
          value: "kafka.kafka.svc.cluster.local:9092"
        - name: topic
          value: "zeus"
        - name: groupID
          value: "analytics-group"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"